### ISSUE TITLE
[feature request] Details for artists in Similar Artists view

### ISSUE THREAD

**Issue by Kixel** [TheWicklowWolf/Lidify#1]
The right panel could use some more info for each artist. 
Currently, i just get a somewhat long list of artists with no idea what kind of music they make. I propose four things:

1. Make each line a bit higher, so it's easier to click on artists
2. Add a link/button to each artist that takes you (in a new tab) to the artist on spotify - so I can check them out and see if I like them
3. Add labels to each artist indicating which genre they belong to (maybe in the style of these labels on github issues).
4. Have the fuzz_ratio (i guess similarity?) as a setting in the app (with reasonable lower bounds?), maybe as a slider (Lidify.py, line 128)

**Comment by TheWicklowWolf** [comment]
The aim was to offer a basic search for well-known-ish artists that are not in your Lidarr library, hence the absence of additional information. Unsure about the necessary info for an informed selection.

---

> * Make each line a bit higher, so it's easier to click on artists

I'll have a look at that, tried to make it compact so I would also kinda work for smaller devices.



> * Add a link/button to each artist that takes you (in a new tab) to the artist on spotify - so I can check them out and see if I like them

Sounds reasonable enough.



> * Add labels to each artist indicating which genre they belong to (maybe in the style of these labels on github issues).

Not a bad suggestion, I'll keep it in mind.

 

> * Have the fuzz_ratio (i guess similarity?) as a setting in the app (with reasonable lower bounds?), maybe as a slider (Lidify.py, line 128)

This is only to make sure that the right artist is found when getting the mbid, the recommendations are as per Spotify Related Artists and there is no real control over that as far as I'm aware.



Feel free to jump in with PRs or fork it if you want
