### ISSUE TITLE
Preview overlay gets stuck

### ISSUE THREAD

**Issue by Kixel** [TheWicklowWolf/Lidify#13]
I (accidently) clicked the preview button twice and it opened two preview clips after each other. clicking outside the preview dialog closes the preview itself and opens the second. clicking outside that preview again dismisses that too, but the darkening background stays. The page is unusable until a reload.

I'd also love to see multiple previews and not just one at the same time (not playing at the same time of course).

BTW fantastic work on the previews, it's pretty much what i wanted when i opened #1

**Comment by TheWicklowWolf** [comment]
> multiple previews

Some artists have multiple previews, and in such instances, a random selection is made from the available options.

I haven't been able to replicate the preview issue, I think it depends on network etc. 
However I'll make it ignore duplicate clicks for 1.5 seconds.

**Comment by TheWicklowWolf** [comment]
see 1ca94e30bd60fa9cb18a322a5d5b986f180ae6f4
