### ISSUE TITLE
Feature request: add logon screen

### ISSUE THREAD

**Issue by terrificobjects** [TheWicklowWolf/Lidify#14]
Just would like to be able to open this to people without the whole world having access! I wasn't sure where else to put this.

**Comment by TheWicklowWolf** [comment]
Great idea and not difficult to implement, but I wouldn't feel comfortable with someone exposing this image to the internet as its outside my wheelhouse. That said,I'd be open to the idea if someone else is willing to submit a PR.

There is work ongoing with Overseer to integrate Lidarr and that might be a better option: 
https://github.com/sct/overseerr/pull/3800
