### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by romprod** [TheWicklowWolf/Lidify#16]
Hi,

I'm trying to set this up but I'm having issues connecting lidify to lidarr but I'm constantly getting this error message back and I'm unable to Lidarr artists.

![image](https://github.com/TheWicklowWolf/Lidify/assets/3393004/493ba5a5-48d0-41fd-8285-f8afc86a85ba)

Can you confirm if my docker-compose setup is correct? I've confirmed connectivity from lidify to lidarr because they can ping each other.

`  lidify:
    image: thewicklowwolf/lidify:latest
    container_name: lidify
    volumes:
      - /hdd/docker/data/lidify/config:/lidify/config
      - /etc/localtime:/etc/localtime:ro
      - /hdd:/hdd
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/London
      - last_fm_api_key=abcdefghijklmnopqrstuvwxyz1234567890
      - lidarr_address=http://172.22.2.14:8686
      - lidarr_api_key=abcdefghijklmnopqrstuvwxyz1234567890
      - root_folder_path=/hdd/storage/music
      - spotify_client_id=abcdefghijklmnopqrstuvwxyz1234567890
      - spotify_client_secret=abcdefghijklmnopqrstuvwxyz1234567890
    restart: unless-stopped
    networks:
      network:
        aliases:
          - lidify`

**Comment by TheWicklowWolf** [comment]
First you should delete this and re-post with your api keys retracted (and maybe best to refresh them in Spotify and Lidarr)

**Comment by TheWicklowWolf** [comment]
can you confirm `/hdd/docker/data/lidify/config` has permissions set for 1000:1000 ?

**Comment by TheWicklowWolf** [comment]
When is this happening and what do the logs say? (Dozzle logs for Lidify)
