### ISSUE TITLE
Name Conversion and Search Result Issues for Japanese Artists and Bands

### ISSUE THREAD

**Issue by symphonyalpha** [TheWicklowWolf/Lidify#17]
Just spun up a container to try this out out and it works great so far, only 2 issues/feedback: 

1. I have many JP artists however, in the Lidify web ui, their names seem to get converted to their CN pinyin instead of the romanji pronunciation. Maybe instead of converting it, their names could be displayed without any conversion, under the assumption that most users should be familiar with how the names of the artists/bands they listen to look like.
2. I follow a Jpop idol band called μ’s however the results from Lidify are entirely neo-soul, R&B artists. I originally thought it might've searched for the english band Muse instead, but that's a rock bank so it couldn't explain the results. Perhaps some check could be implemented by comparing the artist ID on Lidarr to the one on MusicBrainz, then grabbing the Spotify artist URL from there on? There's a Artist-URL relationship type in the MusicBrainz database but I'm not sure if there's retrievable using the MusicBrainz API.

**Comment by TheWicklowWolf** [comment]
Thanks for your suggestions/feedback.

1. There is no conversion on the Lidify side, all data comes from the Spotify API and is presented as is.
2. The recommendation comes from the closest match from Spotify, so maybe there is a mismatch between names.

I don't have any plans to look into this further, but I'm open to PRs if you feel strongly enough about it.
