### ISSUE TITLE
Quality Profile ID

### ISSUE THREAD

**Issue by chesterjazzman** [TheWicklowWolf/Lidify#18]
I don't see a way to find the Quality Profile ID in Lidarr, to set the Lidify environment variable quality_profile_id.  Where can I find that?  I deleted "Standard" which I guess is the default 1.  I want to change to Lossless.

**Comment by chesterjazzman** [comment]
I changed it to 2, and that worked.

**Comment by TheWicklowWolf** [comment]
To get a list of your Quality Profile IDs:
```
curl -X GET "http://<your-lidarr-url>:<port>/api/v1/qualityprofile" \
     -H "X-Api-Key: <your-api-key>"

```

and for MetaData Profile IDs:

```
curl -X GET "http://<your-lidarr-url>:<port>/api/v1/metadata" \
     -H "X-Api-Key: <your-api-key>"
```

**Comment by DeviantEng** [comment]
Slight correct, to get MetaData Profile IDs (Settings > Profiles > Metadata Profiles) you should use this:

```
curl -X GET "http://<your-lidarr-url>:<port>/api/v1/metadataprofile" \
     -H "X-Api-Key: <your-api-key>"
```

What you have listed above will show Metadata Consumers (Settings > Metadata).
