### ISSUE TITLE
Suggested volume mount fix

### ISSUE THREAD

**Issue by winoiknow** [TheWicklowWolf/Lidify#19]
Docker compose needs volume mounted for /config, not /lidify/config per _self.config_folder = "config"_ else receive err on startup = self.lidify_logger.error(f"Error Loading Config: {str(e)}") with permission denied.

Looks pretty good so far. Keep working on it and maybe integrate with your Tube apps for one coherent very useful tool. Not aware of anything else that exists right now that would do this.

Thanks!

**Comment by winoiknow** [comment]
FYI: touching the json then manually entering the proper keys removed permission error but env inputs don't save secrets at startup. Those have to be written to json by hand.
Good luck

**Comment by TheWicklowWolf** [comment]
> Docker compose needs volume mounted for /config, not /lidify/config per _self.config_folder = "config"_ else receive err on startup = self.lidify_logger.error(f"Error Loading Config: {str(e)}") with permission denied.
> 
> Looks pretty good so far. Keep working on it and maybe integrate with your Tube apps for one coherent very useful tool. Not aware of anything else that exists right now that would do this.
> 
> Thanks!

No, the correct folder inside the container is `/lidify/config`
You need to make sure your`/path/to/config` has the correct permission 

<details><summary>docker-compose</summary>
<p>

`/path/to/config:/lidify/config`

The path on the host needs UID:GID permissions to be 1000:1000

</p>
</details> 

> FYI: touching the json then manually entering the proper keys removed permission error but env inputs don't save secrets at startup. Those have to be written to json by hand. Good luck

The issue you are experiencing is because you haven't mapped the correct folder.

**Comment by TheWicklowWolf** [comment]
Permission Error

**Comment by winoiknow** [comment]
Yeah, checked that at first and chmod 777 the directory to ensure permission. It still couldn't create the json. I created the json file and with the mapping it was able to write to it no problem with exception; lidarr address Ok, API key no, Spotify Client Ok, Secret, no, but both the lastfm id and secret were ok.

I wiped everything and started again and same result. Once I wrote the secrets into the json all was well, though.
Not sure if you are able to recreate and I haven't tried local mapping. I do map persistent data to a mounted NFS.

**Comment by TheWicklowWolf** [comment]
> Yeah, checked that at first and chmod 777 the directory to ensure permission. It still couldn't create the json. I created the json file and with the mapping it was able to write to it no problem ~with exception; lidarr address Ok, API key no, Spotify Client Ok, Secret, no, but both the lastfm id and secret were ok.~ Typo on my part, oops.
> 
> I wiped everything and started again and same result. Once I wrote the secrets into the json all was well, though. Not sure if you are able to recreate and ~I haven't tried local mapping~. I do map persistent data to a mounted NFS.


I'm not sure what your exact setup is, but I can't replicate the issue.
Once it has the proper permissions it will write the config file to `/lidify/config` inside the container and subsequently to wherever you have that mapped to.

Maybe just forget about the config file and just use environmental variables defined in the docker compose instead, that way you wont need to map a config folder. 

It's up to you which method you prefer.
