### ISSUE TITLE
Feature : Add Accepted Origins

### ISSUE THREAD

**Issue by timkeefer1** [TheWicklowWolf/Lidify#23]
First install, seems to be working fine (tested adding a band, validated passing thru to Lidarr).  Thanks so much for making this!
However, I'm getting an error when attempting to connect through reverse proxy : 

`https://lidify.xxx.com is not an accepted origin. (further occurrences of this error will be logged with level INFO)`

Can an environment variable be added which validates the origin URL?  And/or an environment variable that disables origin checking?
I poked around in the py a bit, but honestly I'm not good enough to figure out where this is firing from (might be from an import?).

**Comment by TheWicklowWolf** [comment]
This was designed as a stopgap until Overseerr/Jellyseerr has support for music. And as such was only intended for local use and was not designed to be exposed to the internet. 

I'm sure there are way to make harden it for use via reverse proxy but that is not something I plan on adding.
I recommend accessing it within your local network or through a VPN.

Feel free to fork it and change it to suit, best of luck with it.

**Comment by alwayscurious419** [comment]
Thanks for the quick feedback!  Didn't know *seerr had in their roadmap audio support and 100% agree to just wait on that!!
