### ISSUE TITLE
Project Name - maybe change to Similarr ...

### ISSUE THREAD

**Issue by Schmidsfeld** [TheWicklowWolf/Lidify#4]
Dont get me wrong Lidify is a perfectly good name. But I think since it integrated deeply with Lidarr it should have a name reflecting this and fitting into the arr stack.

It is not hard to come up with fitting names - here is a short list of some that might be suitable:
**Similarr** (my personal favorite for this project)
Popularr
Titularr
Singularr
Registrarr
Guitarr

Another good project name would be 
**Spottarr**
if you combine it with your other spottyfy related project Syncify

I have a list of many more if you are interested...

**Comment by TheWicklowWolf** [comment]
Thank you for your suggestions. 
However, that boat has sailed!
It's "Lidify" as **Lid**arr  + Spot**ify**, but I'll keep the names in mind for any future projects.
