### ISSUE TITLE
False message Artist is already in Lidarr.

### ISSUE THREAD

**Issue by bryceprutsos** [TheWicklowWolf/Lidify#7]
Hey just came by to show the app some love.

I noticed that when I have everything setup and select an artist on the webfront it says Artist is already in Lidarr. However looking through the logs it shows this

`lidify    | Artist 'Metro Boomin' matched 'Metro Boomin' with MBID: 59db3d82-86ea-451f-881f-dffc8ec387c9  Ratio: 100
lidify    | Failed to add artist 'Metro Boomin' to Lidarr.
lidify    | {"propertyName": "Path", "errorMessage": "Invalid Path: '/data/media/music/Metro Boomin/'", "attemptedValue": "/data/media/music/Metro Boomin/", "severity": "error", "errorCode": "PathValidator", "formattedMessageArguments": [], "formattedMessagePlaceholderValues": {"path": "/data/media/music/Metro Boomin/", "propertyName": "Path", "propertyValue": "/data/media/music/Metro Boomin/"}}
lidify    | Artist 'Metro Boomin' is already in Lidarr.`

I know its a problem with my Lidarr setup but figured you should know so you can correct the error message back to the user.

**Comment by bryceprutsos** [comment]
Also maybe it could just grab the root folder from Lidarr and can it start searching on add?

**Comment by TheWicklowWolf** [comment]
> Also maybe it could just grab the root folder from Lidarr and can it start searching on add?

In certain scenarios, multiple root folders may exist, necessitating the need for an option to select the desired one.

Thanks for your input.
